parameters:
#    notificaciones.example.class: NotificacionesPush\notificacionesBundle\Example

services:
#    notificaciones.example:
#        class: %notificaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
